"""Medical terminology simplification dictionary. Applied as post-processing after BART summarization. Combined with admin-defined terms from MongoDB."""

import re
from typing import Mapping

MEDICAL_TERMS_DICT = {
  "myocardial infarction": "heart attack",
  "myocardial": "heart muscle",
  "hypertension": "high blood pressure",
  "hypotension": "low blood pressure",
  "tachycardia": "fast heart rate",
  "bradycardia": "slow heart rate",
  "arrhythmia": "irregular heartbeat",
  "atrial fibrillation": "irregular heartbeat (AFib)",
  "atherosclerosis": "hardening of arteries",
  "arteriosclerosis": "hardened blood vessels",
  "angina": "chest pain from heart",
  "angina pectoris": "chest pain",
  "cardiac": "heart-related",
  "cardiology": "heart medicine",
  "cardiomegaly": "enlarged heart",
  "cardiomyopathy": "heart muscle disease",
  "congestive heart failure": "heart failure",
  "heart failure": "heart pump weakness",
  "ischemia": "reduced blood flow",
  "ischemic": "caused by reduced blood flow",
  "thrombosis": "blood clot in vessel",
  "thrombus": "blood clot",
  "embolism": "blocked blood vessel",
  "embolus": "traveling blood clot",
  "stenosis": "narrowing of vessel",
  "palpitation": "noticeable heartbeat",
  "palpitations": "noticeable heartbeats",
  "hypertrophy": "abnormal tissue growth",
  "hypertrophic": "abnormally enlarged",
  "aortic": "related to main artery",
  "ventricular": "related to heart chambers",
  "diastolic": "heart resting pressure",
  "systolic": "heart pumping pressure",
  "dyspnea": "difficulty breathing",
  "dyspnoea": "difficulty breathing",
  "orthopnea": "trouble breathing when lying down",
  "pneumonia": "lung infection",
  "bronchitis": "airway inflammation",
  "bronchial": "airway-related",
  "asthma": "breathing condition",
  "chronic obstructive pulmonary disease": "long-term lung disease",
  "copd": "long-term lung disease",
  "pulmonary": "lung-related",
  "pulmonary embolism": "blood clot in lungs",
  "pneumothorax": "collapsed lung",
  "pleural": "lung lining",
  "pleural effusion": "fluid around lungs",
  "hemoptysis": "coughing up blood",
  "tachypnea": "fast breathing",
  "apnea": "stopped breathing",
  "sleep apnea": "breathing stops during sleep",
  "respiratory": "breathing-related",
  "cyanosis": "bluish skin from low oxygen",
  "hypoxia": "low oxygen levels",
  "hypoxemia": "low oxygen in blood",
  "sputum": "mucus coughed up",
  "expectorant": "mucus-clearing medicine",
  "hepatitis": "liver inflammation",
  "hepatomegaly": "enlarged liver",
  "hepatic": "liver-related",
  "cirrhosis": "liver scarring",
  "cholecystitis": "gallbladder inflammation",
  "cholelithiasis": "gallstones",
  "pancreatitis": "pancreas inflammation",
  "gastritis": "stomach lining inflammation",
  "gastroesophageal reflux": "acid reflux",
  "gerd": "acid reflux",
  "ulcer": "open sore",
  "peptic ulcer": "stomach sore",
  "colitis": "colon inflammation",
  "appendicitis": "appendix inflammation",
  "dysphagia": "difficulty swallowing",
  "nausea": "feeling sick",
  "emesis": "vomiting",
  "diarrhea": "loose stools",
  "constipation": "difficulty passing stool",
  "flatulence": "gas buildup",
  "ascites": "fluid in abdomen",
  "jaundice": "yellowing of skin",
  "icterus": "yellowing of skin",
  "bilirubin": "yellow pigment from liver",
  "bile": "digestive fluid from liver",
  "gastrointestinal": "digestive system",
  "abdomen": "belly area",
  "abdominal": "belly-related",
  "renal insufficiency": "kidney problems",
  "renal failure": "kidney failure",
  "renal": "kidney-related",
  "nephritis": "kidney inflammation",
  "nephrotic": "kidney disease",
  "glomerulonephritis": "kidney filter inflammation",
  "creatinine": "kidney waste marker",
  "urea": "kidney waste product",
  "proteinuria": "protein in urine",
  "hematuria": "blood in urine",
  "oliguria": "reduced urine output",
  "polyuria": "excessive urination",
  "dysuria": "painful urination",
  "urinary tract infection": "bladder/urine infection",
  "uti": "urine infection",
  "cystitis": "bladder inflammation",
  "dialysis": "kidney cleaning treatment",
  "nephrolithiasis": "kidney stones",
  "calculi": "stones in organ",
  "anemia": "low red blood cells",
  "anaemia": "low red blood cells",
  "hyperlipidemia": "high blood fat levels",
  "hypercholesterolemia": "high cholesterol",
  "cholesterol": "blood fat",
  "triglycerides": "blood fats",
  "hemoglobin": "oxygen-carrying blood protein",
  "haemoglobin": "oxygen-carrying blood protein",
  "hematocrit": "blood cell percentage",
  "leukocytosis": "high white blood cell count",
  "leukopenia": "low white blood cell count",
  "thrombocytopenia": "low platelet count",
  "thrombocytosis": "high platelet count",
  "erythrocyte": "red blood cell",
  "leukocyte": "white blood cell",
  "platelet": "blood clotting cell",
  "coagulation": "blood clotting",
  "anticoagulant": "blood thinner",
  "anticoagulation": "blood thinning treatment",
  "sepsis": "severe blood infection",
  "septicemia": "blood poisoning",
  "lymphoma": "lymph node cancer",
  "leukemia": "blood cancer",
  "lymphadenopathy": "swollen lymph nodes",
  "splenomegaly": "enlarged spleen",
  "diabetes mellitus": "diabetes",
  "hyperglycemia": "high blood sugar",
  "hypoglycemia": "low blood sugar",
  "glucose": "blood sugar",
  "glycemia": "blood sugar level",
  "insulin": "blood sugar hormone",
  "hypothyroidism": "underactive thyroid",
  "hyperthyroidism": "overactive thyroid",
  "thyroid": "neck hormone gland",
  "goiter": "enlarged thyroid",
  "adrenal": "stress hormone gland",
  "cortisol": "stress hormone",
  "metabolism": "body energy processing",
  "metabolic": "energy processing",
  "obesity": "excess body weight",
  "bmi": "body weight measure",
  "cerebrovascular accident": "stroke",
  "stroke": "brain blood vessel event",
  "transient ischemic attack": "mini stroke",
  "tia": "mini stroke",
  "dementia": "memory loss condition",
  "alzheimer": "memory loss disease",
  "parkinson": "movement disorder",
  "epilepsy": "seizure disorder",
  "seizure": "sudden brain activity burst",
  "migraine": "severe headache",
  "neuropathy": "nerve damage",
  "peripheral neuropathy": "nerve damage in limbs",
  "radiculopathy": "pinched nerve",
  "meningitis": "brain lining inflammation",
  "encephalitis": "brain inflammation",
  "vertigo": "dizziness/spinning feeling",
  "syncope": "fainting",
  "tremor": "shaking",
  "ataxia": "loss of coordination",
  "paresthesia": "tingling sensation",
  "hemiplegia": "one-sided paralysis",
  "paraplegia": "lower body paralysis",
  "cognitive": "thinking/memory-related",
  "osteoporosis": "weak and brittle bones",
  "osteoarthritis": "joint wear and tear",
  "rheumatoid arthritis": "immune joint disease",
  "arthritis": "joint inflammation",
  "arthralgia": "joint pain",
  "myalgia": "muscle pain",
  "fibromyalgia": "widespread muscle pain",
  "tendinitis": "tendon inflammation",
  "bursitis": "joint cushion inflammation",
  "scoliosis": "curved spine",
  "kyphosis": "hunchback posture",
  "lordosis": "inward curved spine",
  "fracture": "broken bone",
  "dislocation": "joint out of place",
  "sprain": "stretched ligament",
  "strain": "stretched muscle",
  "edema": "swelling from fluid",
  "oedema": "swelling from fluid",
  "inflammation": "swelling and redness",
  "necrosis": "tissue death",
  "fibrosis": "scar tissue formation",
  "atrophy": "tissue wasting",
  "dermatitis": "skin inflammation",
  "eczema": "itchy skin condition",
  "psoriasis": "scaly skin condition",
  "cellulitis": "skin infection",
  "erythema": "skin redness",
  "urticaria": "hives",
  "pruritus": "itching",
  "alopecia": "hair loss",
  "melanoma": "skin cancer",
  "lesion": "abnormal tissue area",
  "macule": "flat skin spot",
  "papule": "raised skin spot",
  "pustule": "pus-filled skin bump",
  "vesicle": "fluid-filled blister",
  "echocardiogram": "heart ultrasound scan",
  "electrocardiogram": "heart electrical test",
  "ecg": "heart electrical test",
  "ekg": "heart electrical test",
  "mri": "magnetic imaging scan",
  "ct scan": "computed tomography scan",
  "x-ray": "bone imaging test",
  "ultrasound": "sound wave imaging scan",
  "endoscopy": "internal camera examination",
  "colonoscopy": "colon camera examination",
  "biopsy": "tissue removal for testing",
  "serology": "blood antibody test",
  "urinalysis": "urine test",
  "spirometry": "lung capacity test",
  "mammography": "breast imaging test",
  "cbc": "complete blood count test",
  "complete blood count": "full blood test",
  "lipid panel": "blood fat test",
  "metabolic panel": "organ function blood test",
  "crp": "inflammation marker test",
  "esr": "inflammation rate test",
  "hba1c": "3-month blood sugar average",
  "hemoglobin a1c": "3-month blood sugar average",
  "catheterization": "tube insertion procedure",
  "intubation": "breathing tube insertion",
  "laparoscopy": "keyhole surgery",
  "angioplasty": "blood vessel opening procedure",
  "stent": "vessel support device",
  "bypass": "rerouted blood flow surgery",
  "amputation": "limb removal surgery",
  "incision": "surgical cut",
  "suture": "stitches",
  "debridement": "wound cleaning",
  "resection": "surgical removal",
  "analgesic": "pain reliever",
  "antipyretic": "fever reducer",
  "antibiotic": "bacterial infection medicine",
  "antihypertensive": "blood pressure medicine",
  "antidiabetic": "diabetes medicine",
  "bronchodilator": "airway opener",
  "diuretic": "water pill",
  "corticosteroid": "steroid medicine",
  "nsaid": "anti-inflammatory pain medicine",
  "statin": "cholesterol-lowering medicine",
  "beta blocker": "heart rate medicine",
  "ace inhibitor": "blood pressure medicine",
  "vasodilator": "blood vessel widener",
  "sedative": "calming medicine",
  "antiemetic": "anti-nausea medicine",
  "laxative": "bowel movement medicine",
  "prophylaxis": "preventive treatment",
  "intravenous": "given through vein",
  "subcutaneous": "given under skin",
  "intramuscular": "given into muscle",
  "oral": "taken by mouth",
  "topical": "applied to skin",
  "acute": "sudden/short-term",
  "chronic": "long-lasting",
  "benign": "non-cancerous",
  "malignant": "cancerous",
  "etiology": "cause of disease",
  "prognosis": "expected outcome",
  "diagnosis": "identified condition",
  "pathology": "disease study",
  "pathological": "disease-related abnormal",
  "idiopathic": "unknown cause",
  "symptomatic": "showing symptoms",
  "asymptomatic": "no symptoms",
  "subclinical": "below detectable symptoms",
  "bilateral": "both sides",
  "unilateral": "one side only",
  "proximal": "closer to body center",
  "distal": "further from body center",
  "anterior": "front side",
  "posterior": "back side",
  "lateral": "side",
  "medial": "middle",
  "superior": "upper",
  "inferior": "lower",
  "contraindication": "reason not to use treatment",
  "complication": "additional problem from disease",
  "comorbidity": "additional medical condition",
  "morbidity": "illness",
  "mortality": "death rate",
  "remission": "disease improving/gone",
  "relapse": "disease returning",
  "exacerbation": "worsening of condition",
  "palliation": "comfort care",
  "palliative": "comfort-focused care",
  "prophylactic": "preventive",
  "therapeutic": "treatment-related",
  "intervention": "medical treatment",
  "regimen": "treatment plan",
  "protocol": "treatment guideline",
  "indication": "reason for treatment",
  "adverse": "harmful/negative",
  "toxicity": "harmful level",
  "contraindicated": "should not be used",
  "disposition": "treatment outcome plan",
  "follow-up": "check-up appointment",
  "workup": "medical investigation",
  "differential": "possible diagnoses",
  "vital signs": "basic health measurements",
  "pyrexia": "fever",
  "febrile": "having fever",
  "afebrile": "no fever",
  "diaphoresis": "excessive sweating",
  "pallor": "pale appearance",
  "crepitus": "crackling sound in joint",
  "murmur": "abnormal heart sound",
  "effusion": "abnormal fluid buildup",
  "abscess": "pus-filled infection",
  "perforation": "hole in organ",
  "obstruction": "blockage",
  "stricture": "abnormal narrowing",
  "fistula": "abnormal tunnel between organs"
}


def get_python_terms() -> dict:
  return MEDICAL_TERMS_DICT.copy()


def merge_medical_term_maps(
  base: dict[str, str],
  extra: Mapping[str, str] | None,
) -> dict[str, str]:
  """
  Overlay admin / DB terms on built-ins. Same phrase (case-insensitive) uses the extra mapping.
  """
  if not extra:
    return dict(base)
  merged = dict(base)
  lower_to_key = {k.lower(): k for k in merged}
  for mk_raw, sv_raw in extra.items():
    mk_clean = str(mk_raw).strip()
    sv_clean = str(sv_raw).strip()
    if not mk_clean or not sv_clean:
      continue
    lk = mk_clean.lower()
    old = lower_to_key.get(lk)
    if old is not None:
      del merged[old]
    merged[mk_clean] = sv_clean
    lower_to_key[lk] = mk_clean
  return merged


def apply_terms(text: str, extra_terms: dict | None = None) -> dict:
  merged = merge_medical_term_maps(MEDICAL_TERMS_DICT, extra_terms)
  ordered = sorted(merged.items(), key=lambda kv: len(kv[0]), reverse=True)
  result = text
  replacements_made: list[dict[str, str]] = []
  for medical, simple in ordered:
    pattern = re.compile(r"\b" + re.escape(medical) + r"\b", re.IGNORECASE)
    new_result, count = pattern.subn(simple, result)
    if count:
      replacements_made.append({"original": medical, "replacement": simple})
      result = new_result
  return {"simplified_text": result, "replacements_made": replacements_made}


# Backward compatibility
MEDICAL_TERMS = dict(sorted(MEDICAL_TERMS_DICT.items(), key=lambda kv: kv[0].lower()))


def simplify_medical_terms(text: str, extra_medical_terms: Mapping[str, str] | None = None) -> str:
  return apply_terms(text, extra_terms=extra_medical_terms)["simplified_text"]
