/**
 * Mirrors ai-service/app/services/medical_terms.py `_MEDICAL_TERMS_RAW`
 * for doctor UI “Medical Terms Simplified” hints (same keys/values).
 */
export const MEDICAL_TERM_PAIRS = {
  hypertension: 'high blood pressure',
  hyperlipidemia: 'high cholesterol',
  'myocardial infarction': 'heart attack',
  'renal insufficiency': 'kidney problems',
  dyspnea: 'difficulty breathing',
  tachycardia: 'fast heart rate',
  anemia: 'low red blood cells',
  hepatomegaly: 'enlarged liver',
  bradycardia: 'slow heart rate',
  hypertrophy: 'abnormal enlargement',
  ischemia: 'reduced blood flow',
  'myocardial ischemia': 'reduced blood flow',
  edema: 'swelling',
  arrhythmia: 'irregular heartbeat',
  atherosclerosis: 'hardening of arteries',
  thrombosis: 'blood clot',
  embolism: 'blocked blood vessel',
  infarction: 'tissue death from blocked blood',
  stenosis: 'narrowing',
  fibrosis: 'scarring of tissue',
  necrosis: 'tissue death',
  sepsis: 'severe infection in bloodstream',
  pneumonia: 'lung infection',
  hypoglycemia: 'low blood sugar',
  hyperglycemia: 'high blood sugar',
  'diabetes mellitus': 'diabetes',
  osteoporosis: 'weak and brittle bones',
  arthritis: 'joint inflammation',
  dermatitis: 'skin inflammation',
  gastritis: 'stomach lining inflammation',
  hepatitis: 'liver inflammation',
  nephritis: 'kidney inflammation',
  appendicitis: 'appendix inflammation',
  bronchitis: 'airway inflammation',
  pancreatitis: 'pancreas inflammation',
  cholesterol: 'fatty substance in blood',
  glucose: 'blood sugar',
  hemoglobin: 'oxygen-carrying protein in blood',
  leukocyte: 'white blood cell',
  erythrocyte: 'red blood cell',
  platelet: 'blood clotting cell',
  serum: 'liquid part of blood',
  biopsy: 'tissue sample test',
  catheter: 'thin tube inserted in body',
  dialysis: 'kidney filtering treatment',
  echocardiogram: 'heart ultrasound',
  electrocardiogram: 'heart electrical activity test',
  endoscopy: 'internal camera examination',
  mammography: 'breast X-ray',
  laparoscopy: 'keyhole surgery examination',
};
