import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'react-toastify';
import { formatDateInPakistan, formatTimeInPakistan } from './isoDate.js';

export const exportAnalyticsPDF = ({
  title,
  subtitle,
  tableHeaders,
  tableData,
  summaryStats,
  dateRange,
}) => {
  if (!Array.isArray(tableData) || tableData.length === 0) {
    toast.warning('No data to export');
    return;
  }

  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.setTextColor(13, 148, 136);
  doc.text('CareConnect 360', 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text(title || 'Analytics Report', 14, 32);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(subtitle || 'Operational analytics report', 14, 40);
  doc.text(`Period: ${dateRange?.from || '-'} to ${dateRange?.to || '-'}`, 14, 48);
  doc.text(`Generated: ${formatDateInPakistan(new Date())} ${formatTimeInPakistan(new Date())}`, 14, 56);

  if (Array.isArray(summaryStats) && summaryStats.length > 0) {
    let x = 14;
    summaryStats.forEach((stat) => {
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(String(stat.label || ''), x, 68);
      doc.setFontSize(13);
      doc.setTextColor(13, 148, 136);
      doc.text(String(stat.value ?? ''), x, 76);
      x += 48;
    });
  }

  autoTable(doc, {
    head: [tableHeaders || []],
    body: tableData || [],
    startY: summaryStats && summaryStats.length > 0 ? 85 : 65,
    styles: {
      fontSize: 9,
      cellPadding: 4,
      textColor: [30, 41, 59],
    },
    headStyles: {
      fillColor: [13, 148, 136],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    foot: [['', '', '', '', 'Generated by CareConnect 360']],
    footStyles: { textColor: [100, 116, 139], fontSize: 8 },
  });

  const safeTitle = String(title || 'Analytics').replace(/\s+/g, '-');
  doc.save(`CareConnect-${safeTitle}-${dateRange?.from || 'report'}.pdf`);
  toast.success('PDF exported successfully');
};
